# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: Halim-m

      # Debugging Step: Check Output
      - name: Debugging Generate Snake Animation
        run: |
          echo "Debugging Generate Snake Animation..."
          ls -la
          ls -la ./dist || echo "Dist directory not found!"

      # Step 3: Upload Snake Animation to GitHub Pages
      - name: Upload Snake Animation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist
