# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: Halim-m

      # Debugging Step: Check Output
      - name: Debugging Generate Snake Animation
        run: |
          echo "Debugging Generate Snake Animation..."
          ls -la
          ls -la ./dist || echo "Dist directory not found!"

      # Step 3: Commit and Push Snake Animation to Repository
      - name: Commit and Push Snake Animation
        run: |
          echo "Adding snake.svg to the repository..."
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/snake.svg
          git commit -m "Add updated snake.svg"
          git push origin main
