# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run.
on:
  schedule:
      # every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Halim-m
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Debugging Step: Check Generated Files
      - name: Debugging Generated Files
        run: |
          echo "Checking generated files..."
          ls -la dist

      # Step 3: Commit and Push Snake Animation to Repository
      - name: Commit and Push Snake Animation
        uses: ad-m/github-push-action@v0.6
        with:
          github_token: ${{ secrets.GH_PAT }}
          branch: main
          force: true
          message: "Updated snake animation"

      # Step 4: Upload Snake Animation to GitHub Pages
      - name: Upload Snake Animation to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
