# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  push:
    branches:
      - main
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@v3.2.0
        with:
          github_user_name: ${{ github.repository_owner }}

      # Debugging Step 1: List Files in Project Root
      - name: DebuggingDirectory
        run: |
          echo "Root Directory Contents:"
          ls -la

      # Debugging Step 2: Check Contents of Dist Directory
      - name: DebuggingDist
        run: |
          echo "Dist Directory Contents:"
          if [ -d "./dist" ]; then
            ls -la ./dist
          else
            echo "Dist directory does not exist!"
            exit 1
          fi

      # Step 3: Upload Snake Animation to GitHub Pages
      - name: Upload Snake Animation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./dist

      # Debugging Step 3: Confirm Upload Success
      - name: Confirm GitHub Pages Deployment
        run: |
          echo "Deployment should now be live. Please check the URL:"
          echo "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/snake.svg"
